/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import com.jakala.menarini.core.entities.utils.Indexes;
import com.jakala.menarini.core.entities.utils.Keys;
import com.jakala.menarini.core.entities.utils.DbSchema;
import com.jakala.menarini.core.entities.records.EventRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event extends TableImpl<EventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>menarini_dev.EVENT</code>
     */
    public static final Event EVENT = new Event();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventRecord> getRecordType() {
        return EventRecord.class;
    }

    /**
     * The column <code>menarini_dev.EVENT.id</code>.
     */
    public final TableField<EventRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>menarini_dev.EVENT.event_type</code>.
     */
    public final TableField<EventRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>menarini_dev.EVENT.title</code>.
     */
    public final TableField<EventRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>menarini_dev.EVENT.description</code>.
     */
    public final TableField<EventRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>menarini_dev.EVENT.coordinators</code>.
     */
    public final TableField<EventRecord, String> COORDINATORS = createField(DSL.name("coordinators"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>menarini_dev.EVENT.subscription</code>.
     */
    public final TableField<EventRecord, String> SUBSCRIPTION = createField(DSL.name("subscription"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>menarini_dev.EVENT.start_date</code>.
     */
    public final TableField<EventRecord, LocalDate> START_DATE = createField(DSL.name("start_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>menarini_dev.EVENT.end_date</code>.
     */
    public final TableField<EventRecord, LocalDate> END_DATE = createField(DSL.name("end_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>menarini_dev.EVENT.location_id</code>.
     */
    public final TableField<EventRecord, Long> LOCATION_ID = createField(DSL.name("location_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>menarini_dev.EVENT.venue_id</code>.
     */
    public final TableField<EventRecord, Long> VENUE_ID = createField(DSL.name("venue_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>menarini_dev.EVENT.created_on</code>.
     */
    public final TableField<EventRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>menarini_dev.EVENT.last_updated_on</code>.
     */
    public final TableField<EventRecord, LocalDateTime> LAST_UPDATED_ON = createField(DSL.name("last_updated_on"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Event(Name alias, Table<EventRecord> aliased) {
        this(alias, aliased, null);
    }

    private Event(Name alias, Table<EventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>menarini_dev.EVENT</code> table reference
     */
    public Event(String alias) {
        this(DSL.name(alias), EVENT);
    }

    /**
     * Create an aliased <code>menarini_dev.EVENT</code> table reference
     */
    public Event(Name alias) {
        this(alias, EVENT);
    }

    /**
     * Create a <code>menarini_dev.EVENT</code> table reference
     */
    public Event() {
        this(DSL.name("EVENT"), null);
    }

    public <O extends Record> Event(Table<O> child, ForeignKey<O, EventRecord> key) {
        super(child, key, EVENT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DbSchema.MENARINI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.EVENT_LOCATION_ID, Indexes.EVENT_VENUE_ID);
    }

    @Override
    public Identity<EventRecord, Long> getIdentity() {
        return (Identity<EventRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EventRecord> getPrimaryKey() {
        return Keys.KEY_EVENT_PRIMARY;
    }

    @Override
    public List<ForeignKey<EventRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EVENT_IBFK_1, Keys.EVENT_IBFK_2);
    }

    private transient Location _location;
    private transient Venue _venue;

    /**
     * Get the implicit join path to the <code>menarini_dev.LOCATION</code>
     * table.
     */
    public Location location() {
        if (_location == null)
            _location = new Location(this, Keys.EVENT_IBFK_1);

        return _location;
    }

    /**
     * Get the implicit join path to the <code>menarini_dev.VENUE</code> table.
     */
    public Venue venue() {
        if (_venue == null)
            _venue = new Venue(this, Keys.EVENT_IBFK_2);

        return _venue;
    }

    @Override
    public Event as(String alias) {
        return new Event(DSL.name(alias), this);
    }

    @Override
    public Event as(Name alias) {
        return new Event(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Event rename(String name) {
        return new Event(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Event rename(Name name) {
        return new Event(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, String, LocalDate, LocalDate, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
