/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import com.jakala.menarini.core.entities.utils.Indexes;
import com.jakala.menarini.core.entities.utils.Keys;
import com.jakala.menarini.core.entities.utils.DbSchema;
import com.jakala.menarini.core.entities.records.NewsletterSubscriptionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsletterSubscription extends TableImpl<NewsletterSubscriptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>menarini_dev.NEWSLETTER_SUBSCRIPTION</code>
     */
    public static final NewsletterSubscription NEWSLETTER_SUBSCRIPTION = new NewsletterSubscription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NewsletterSubscriptionRecord> getRecordType() {
        return NewsletterSubscriptionRecord.class;
    }

    /**
     * The column <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.id</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.lastname</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, String> LASTNAME = createField(DSL.name("lastname"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.firstname</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, String> FIRSTNAME = createField(DSL.name("firstname"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.email</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.occupation</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, String> OCCUPATION = createField(DSL.name("occupation"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.personal_data_processing_consent</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, String> PERSONAL_DATA_PROCESSING_CONSENT = createField(DSL.name("personal_data_processing_consent"), SQLDataType.CHAR(1), this, "");

    /**
     * The column
     * <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.personal_data_processing_consent_ts</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, LocalDateTime> PERSONAL_DATA_PROCESSING_CONSENT_TS = createField(DSL.name("personal_data_processing_consent_ts"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.newsletter_subscription</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, String> NEWSLETTER_SUBSCRIPTION_ = createField(DSL.name("newsletter_subscription"), SQLDataType.CHAR(1), this, "");

    /**
     * The column
     * <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.newsletter_subscription_ts</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, LocalDateTime> NEWSLETTER_SUBSCRIPTION_TS = createField(DSL.name("newsletter_subscription_ts"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.registered_user_id</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, Long> REGISTERED_USER_ID = createField(DSL.name("registered_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.created_on</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.last_updated_on</code>.
     */
    public final TableField<NewsletterSubscriptionRecord, LocalDateTime> LAST_UPDATED_ON = createField(DSL.name("last_updated_on"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private NewsletterSubscription(Name alias, Table<NewsletterSubscriptionRecord> aliased) {
        this(alias, aliased, null);
    }

    private NewsletterSubscription(Name alias, Table<NewsletterSubscriptionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>menarini_dev.NEWSLETTER_SUBSCRIPTION</code> table
     * reference
     */
    public NewsletterSubscription(String alias) {
        this(DSL.name(alias), NEWSLETTER_SUBSCRIPTION);
    }

    /**
     * Create an aliased <code>menarini_dev.NEWSLETTER_SUBSCRIPTION</code> table
     * reference
     */
    public NewsletterSubscription(Name alias) {
        this(alias, NEWSLETTER_SUBSCRIPTION);
    }

    /**
     * Create a <code>menarini_dev.NEWSLETTER_SUBSCRIPTION</code> table
     * reference
     */
    public NewsletterSubscription() {
        this(DSL.name("NEWSLETTER_SUBSCRIPTION"), null);
    }

    public <O extends Record> NewsletterSubscription(Table<O> child, ForeignKey<O, NewsletterSubscriptionRecord> key) {
        super(child, key, NEWSLETTER_SUBSCRIPTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DbSchema.MENARINI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.NEWSLETTER_SUBSCRIPTION_REGISTERED_USER_ID);
    }

    @Override
    public Identity<NewsletterSubscriptionRecord, Long> getIdentity() {
        return (Identity<NewsletterSubscriptionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<NewsletterSubscriptionRecord> getPrimaryKey() {
        return Keys.KEY_NEWSLETTER_SUBSCRIPTION_PRIMARY;
    }

    @Override
    public List<ForeignKey<NewsletterSubscriptionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NEWSLETTER_SUBSCRIPTION_IBFK_1);
    }

    private transient RegisteredUser _registeredUser;

    /**
     * Get the implicit join path to the
     * <code>menarini_dev.REGISTERED_USER</code> table.
     */
    public RegisteredUser registeredUser() {
        if (_registeredUser == null)
            _registeredUser = new RegisteredUser(this, Keys.NEWSLETTER_SUBSCRIPTION_IBFK_1);

        return _registeredUser;
    }

    @Override
    public NewsletterSubscription as(String alias) {
        return new NewsletterSubscription(DSL.name(alias), this);
    }

    @Override
    public NewsletterSubscription as(Name alias) {
        return new NewsletterSubscription(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NewsletterSubscription rename(String name) {
        return new NewsletterSubscription(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NewsletterSubscription rename(Name name) {
        return new NewsletterSubscription(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, String, LocalDateTime, String, LocalDateTime, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
