/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import com.jakala.menarini.core.entities.utils.Indexes;
import com.jakala.menarini.core.entities.utils.Keys;
import com.jakala.menarini.core.entities.utils.DbSchema;
import com.jakala.menarini.core.entities.records.RegisteredUserTopicRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisteredUserTopic extends TableImpl<RegisteredUserTopicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>menarini_dev.REGISTERED_USER_TOPIC</code>
     */
    public static final RegisteredUserTopic REGISTERED_USER_TOPIC = new RegisteredUserTopic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RegisteredUserTopicRecord> getRecordType() {
        return RegisteredUserTopicRecord.class;
    }

    /**
     * The column <code>menarini_dev.REGISTERED_USER_TOPIC.id</code>.
     */
    public final TableField<RegisteredUserTopicRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>menarini_dev.REGISTERED_USER_TOPIC.seq_no</code>.
     */
    public final TableField<RegisteredUserTopicRecord, Integer> SEQ_NO = createField(DSL.name("seq_no"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>menarini_dev.REGISTERED_USER_TOPIC.topic_id</code>.
     */
    public final TableField<RegisteredUserTopicRecord, Long> TOPIC_ID = createField(DSL.name("topic_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>menarini_dev.REGISTERED_USER_TOPIC.registered_user_id</code>.
     */
    public final TableField<RegisteredUserTopicRecord, Long> REGISTERED_USER_ID = createField(DSL.name("registered_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>menarini_dev.REGISTERED_USER_TOPIC.created_on</code>.
     */
    public final TableField<RegisteredUserTopicRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>menarini_dev.REGISTERED_USER_TOPIC.last_updated_on</code>.
     */
    public final TableField<RegisteredUserTopicRecord, LocalDateTime> LAST_UPDATED_ON = createField(DSL.name("last_updated_on"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private RegisteredUserTopic(Name alias, Table<RegisteredUserTopicRecord> aliased) {
        this(alias, aliased, null);
    }

    private RegisteredUserTopic(Name alias, Table<RegisteredUserTopicRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>menarini_dev.REGISTERED_USER_TOPIC</code> table
     * reference
     */
    public RegisteredUserTopic(String alias) {
        this(DSL.name(alias), REGISTERED_USER_TOPIC);
    }

    /**
     * Create an aliased <code>menarini_dev.REGISTERED_USER_TOPIC</code> table
     * reference
     */
    public RegisteredUserTopic(Name alias) {
        this(alias, REGISTERED_USER_TOPIC);
    }

    /**
     * Create a <code>menarini_dev.REGISTERED_USER_TOPIC</code> table reference
     */
    public RegisteredUserTopic() {
        this(DSL.name("REGISTERED_USER_TOPIC"), null);
    }

    public <O extends Record> RegisteredUserTopic(Table<O> child, ForeignKey<O, RegisteredUserTopicRecord> key) {
        super(child, key, REGISTERED_USER_TOPIC);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DbSchema.MENARINI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.REGISTERED_USER_TOPIC_REGISTERED_USER_ID, Indexes.REGISTERED_USER_TOPIC_TOPIC_ID);
    }

    @Override
    public Identity<RegisteredUserTopicRecord, Long> getIdentity() {
        return (Identity<RegisteredUserTopicRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RegisteredUserTopicRecord> getPrimaryKey() {
        return Keys.KEY_REGISTERED_USER_TOPIC_PRIMARY;
    }

    @Override
    public List<ForeignKey<RegisteredUserTopicRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REGISTERED_USER_TOPIC_IBFK_1, Keys.REGISTERED_USER_TOPIC_IBFK_2);
    }

    private transient Topic _topic;
    private transient RegisteredUser _registeredUser;

    /**
     * Get the implicit join path to the <code>menarini_dev.TOPIC</code> table.
     */
    public Topic topic() {
        if (_topic == null)
            _topic = new Topic(this, Keys.REGISTERED_USER_TOPIC_IBFK_1);

        return _topic;
    }

    /**
     * Get the implicit join path to the
     * <code>menarini_dev.REGISTERED_USER</code> table.
     */
    public RegisteredUser registeredUser() {
        if (_registeredUser == null)
            _registeredUser = new RegisteredUser(this, Keys.REGISTERED_USER_TOPIC_IBFK_2);

        return _registeredUser;
    }

    @Override
    public RegisteredUserTopic as(String alias) {
        return new RegisteredUserTopic(DSL.name(alias), this);
    }

    @Override
    public RegisteredUserTopic as(Name alias) {
        return new RegisteredUserTopic(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RegisteredUserTopic rename(String name) {
        return new RegisteredUserTopic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RegisteredUserTopic rename(Name name) {
        return new RegisteredUserTopic(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Integer, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
