/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import com.jakala.menarini.core.entities.utils.Indexes;
import com.jakala.menarini.core.entities.utils.Keys;
import com.jakala.menarini.core.entities.utils.DbSchema;
import com.jakala.menarini.core.entities.records.VenueRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Venue extends TableImpl<VenueRecord> {

    private static final long serialVersionUID = 1629891455;

    /**
     * The reference instance of <code>menarini_dev.VENUE</code>
     */
    public static final Venue VENUE = new Venue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VenueRecord> getRecordType() {
        return VenueRecord.class;
    }

    /**
     * The column <code>menarini_dev.VENUE.id</code>.
     */
    public final TableField<VenueRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>menarini_dev.VENUE.location_id</code>.
     */
    public final TableField<VenueRecord, Long> LOCATION_ID = createField("location_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>menarini_dev.VENUE.name</code>.
     */
    public final TableField<VenueRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>menarini_dev.VENUE.description</code>.
     */
    public final TableField<VenueRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>menarini_dev.VENUE.notes</code>.
     */
    public final TableField<VenueRecord, String> NOTES = createField("notes", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>menarini_dev.VENUE.created_on</code>.
     */
    public final TableField<VenueRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>menarini_dev.VENUE.last_updated_on</code>.
     */
    public final TableField<VenueRecord, Timestamp> LAST_UPDATED_ON = createField("last_updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>menarini_dev.VENUE</code> table reference
     */
    public Venue() {
        this(DSL.name("VENUE"), null);
    }

    /**
     * Create an aliased <code>menarini_dev.VENUE</code> table reference
     */
    public Venue(String alias) {
        this(DSL.name(alias), VENUE);
    }

    /**
     * Create an aliased <code>menarini_dev.VENUE</code> table reference
     */
    public Venue(Name alias) {
        this(alias, VENUE);
    }

    private Venue(Name alias, Table<VenueRecord> aliased) {
        this(alias, aliased, null);
    }

    private Venue(Name alias, Table<VenueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Venue(Table<O> child, ForeignKey<O, VenueRecord> key) {
        super(child, key, VENUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbSchema.MENARINI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VENUE_LOCATION_ID, Indexes.VENUE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VenueRecord, Long> getIdentity() {
        return Keys.IDENTITY_VENUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VenueRecord> getPrimaryKey() {
        return Keys.KEY_VENUE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VenueRecord>> getKeys() {
        return Arrays.<UniqueKey<VenueRecord>>asList(Keys.KEY_VENUE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VenueRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VenueRecord, ?>>asList(Keys.VENUE_IBFK_1);
    }

    public Location location() {
        return new Location(this, Keys.VENUE_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Venue as(String alias) {
        return new Venue(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Venue as(Name alias) {
        return new Venue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Venue rename(String name) {
        return new Venue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Venue rename(Name name) {
        return new Venue(name, null);
    }
}
