/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import com.jakala.menarini.core.entities.EventSessionDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventSessionDateRecord extends UpdatableRecordImpl<EventSessionDateRecord> implements Record9<Long, String, Integer, LocalDate, Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.session</code>.
     */
    public void setSession(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.session</code>.
     */
    public String getSession() {
        return (String) get(1);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.seq_no</code>.
     */
    public void setSeqNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.seq_no</code>.
     */
    public Integer getSeqNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.session_date</code>.
     */
    public void setSessionDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.session_date</code>.
     */
    public LocalDate getSessionDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.venue_id</code>.
     */
    public void setVenueId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.venue_id</code>.
     */
    public Long getVenueId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.event_id</code>.
     */
    public void setEventId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.last_updated_on</code>.
     */
    public void setLastUpdatedOn(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.last_updated_on</code>.
     */
    public LocalDateTime getLastUpdatedOn() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, Integer, LocalDate, Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, Integer, LocalDate, Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EventSessionDate.EVENT_SESSION_DATE.ID;
    }

    @Override
    public Field<String> field2() {
        return EventSessionDate.EVENT_SESSION_DATE.SESSION;
    }

    @Override
    public Field<Integer> field3() {
        return EventSessionDate.EVENT_SESSION_DATE.SEQ_NO;
    }

    @Override
    public Field<LocalDate> field4() {
        return EventSessionDate.EVENT_SESSION_DATE.SESSION_DATE;
    }

    @Override
    public Field<Long> field5() {
        return EventSessionDate.EVENT_SESSION_DATE.LOCATION_ID;
    }

    @Override
    public Field<Long> field6() {
        return EventSessionDate.EVENT_SESSION_DATE.VENUE_ID;
    }

    @Override
    public Field<Long> field7() {
        return EventSessionDate.EVENT_SESSION_DATE.EVENT_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return EventSessionDate.EVENT_SESSION_DATE.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return EventSessionDate.EVENT_SESSION_DATE.LAST_UPDATED_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSession();
    }

    @Override
    public Integer component3() {
        return getSeqNo();
    }

    @Override
    public LocalDate component4() {
        return getSessionDate();
    }

    @Override
    public Long component5() {
        return getLocationId();
    }

    @Override
    public Long component6() {
        return getVenueId();
    }

    @Override
    public Long component7() {
        return getEventId();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component9() {
        return getLastUpdatedOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSession();
    }

    @Override
    public Integer value3() {
        return getSeqNo();
    }

    @Override
    public LocalDate value4() {
        return getSessionDate();
    }

    @Override
    public Long value5() {
        return getLocationId();
    }

    @Override
    public Long value6() {
        return getVenueId();
    }

    @Override
    public Long value7() {
        return getEventId();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value9() {
        return getLastUpdatedOn();
    }

    @Override
    public EventSessionDateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EventSessionDateRecord value2(String value) {
        setSession(value);
        return this;
    }

    @Override
    public EventSessionDateRecord value3(Integer value) {
        setSeqNo(value);
        return this;
    }

    @Override
    public EventSessionDateRecord value4(LocalDate value) {
        setSessionDate(value);
        return this;
    }

    @Override
    public EventSessionDateRecord value5(Long value) {
        setLocationId(value);
        return this;
    }

    @Override
    public EventSessionDateRecord value6(Long value) {
        setVenueId(value);
        return this;
    }

    @Override
    public EventSessionDateRecord value7(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public EventSessionDateRecord value8(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public EventSessionDateRecord value9(LocalDateTime value) {
        setLastUpdatedOn(value);
        return this;
    }

    @Override
    public EventSessionDateRecord values(Long value1, String value2, Integer value3, LocalDate value4, Long value5, Long value6, Long value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventSessionDateRecord
     */
    public EventSessionDateRecord() {
        super(EventSessionDate.EVENT_SESSION_DATE);
    }

    /**
     * Create a detached, initialised EventSessionDateRecord
     */
    public EventSessionDateRecord(Long id, String session, Integer seqNo, LocalDate sessionDate, Long locationId, Long venueId, Long eventId, LocalDateTime createdOn, LocalDateTime lastUpdatedOn) {
        super(EventSessionDate.EVENT_SESSION_DATE);

        setId(id);
        setSession(session);
        setSeqNo(seqNo);
        setSessionDate(sessionDate);
        setLocationId(locationId);
        setVenueId(venueId);
        setEventId(eventId);
        setCreatedOn(createdOn);
        setLastUpdatedOn(lastUpdatedOn);
    }
}
