/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.time.LocalDateTime;

import com.jakala.menarini.core.entities.EventSpeaker;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventSpeakerRecord extends UpdatableRecordImpl<EventSpeakerRecord> implements Record5<Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>menarini_dev.EVENT_SPEAKER.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SPEAKER.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SPEAKER.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SPEAKER.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SPEAKER.speaker_id</code>.
     */
    public void setSpeakerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SPEAKER.speaker_id</code>.
     */
    public Long getSpeakerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SPEAKER.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SPEAKER.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SPEAKER.last_updated_on</code>.
     */
    public void setLastUpdatedOn(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SPEAKER.last_updated_on</code>.
     */
    public LocalDateTime getLastUpdatedOn() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EventSpeaker.EVENT_SPEAKER.ID;
    }

    @Override
    public Field<Long> field2() {
        return EventSpeaker.EVENT_SPEAKER.EVENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return EventSpeaker.EVENT_SPEAKER.SPEAKER_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return EventSpeaker.EVENT_SPEAKER.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return EventSpeaker.EVENT_SPEAKER.LAST_UPDATED_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getEventId();
    }

    @Override
    public Long component3() {
        return getSpeakerId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component5() {
        return getLastUpdatedOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getEventId();
    }

    @Override
    public Long value3() {
        return getSpeakerId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value5() {
        return getLastUpdatedOn();
    }

    @Override
    public EventSpeakerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EventSpeakerRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public EventSpeakerRecord value3(Long value) {
        setSpeakerId(value);
        return this;
    }

    @Override
    public EventSpeakerRecord value4(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public EventSpeakerRecord value5(LocalDateTime value) {
        setLastUpdatedOn(value);
        return this;
    }

    @Override
    public EventSpeakerRecord values(Long value1, Long value2, Long value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventSpeakerRecord
     */
    public EventSpeakerRecord() {
        super(EventSpeaker.EVENT_SPEAKER);
    }

    /**
     * Create a detached, initialised EventSpeakerRecord
     */
    public EventSpeakerRecord(Long id, Long eventId, Long speakerId, LocalDateTime createdOn, LocalDateTime lastUpdatedOn) {
        super(EventSpeaker.EVENT_SPEAKER);

        setId(id);
        setEventId(eventId);
        setSpeakerId(speakerId);
        setCreatedOn(createdOn);
        setLastUpdatedOn(lastUpdatedOn);
    }
}
