/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import com.jakala.menarini.core.entities.EventEnrollment;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventEnrollmentRecord extends UpdatableRecordImpl<EventEnrollmentRecord> implements Record10<Long, Long, Long, String, Timestamp, String, Timestamp, Object, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1349107496;

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.registered_user_id</code>.
     */
    public void setRegisteredUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.registered_user_id</code>.
     */
    public Long getRegisteredUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.is_live_stream</code>.
     */
    public void setIsLiveStream(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.is_live_stream</code>.
     */
    public String getIsLiveStream() {
        return (String) get(3);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.live_stream_registration_ts</code>.
     */
    public void setLiveStreamRegistrationTs(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.live_stream_registration_ts</code>.
     */
    public Timestamp getLiveStreamRegistrationTs() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.is_residential</code>.
     */
    public void setIsResidential(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.is_residential</code>.
     */
    public String getIsResidential() {
        return (String) get(5);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.residential_registration_ts</code>.
     */
    public void setResidentialRegistrationTs(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.residential_registration_ts</code>.
     */
    public Timestamp getResidentialRegistrationTs() {
        return (Timestamp) get(6);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setInPersonParticipationDateList(Object value) {
        set(7, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getInPersonParticipationDateList() {
        return get(7);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_ENROLLMENT.last_updated_on</code>.
     */
    public void setLastUpdatedOn(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_ENROLLMENT.last_updated_on</code>.
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, String, Timestamp, String, Timestamp, Object, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, String, Timestamp, String, Timestamp, Object, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EventEnrollment.EVENT_ENROLLMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return EventEnrollment.EVENT_ENROLLMENT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return EventEnrollment.EVENT_ENROLLMENT.REGISTERED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return EventEnrollment.EVENT_ENROLLMENT.IS_LIVE_STREAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return EventEnrollment.EVENT_ENROLLMENT.LIVE_STREAM_REGISTRATION_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return EventEnrollment.EVENT_ENROLLMENT.IS_RESIDENTIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return EventEnrollment.EVENT_ENROLLMENT.RESIDENTIAL_REGISTRATION_TS;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field8() {
        return EventEnrollment.EVENT_ENROLLMENT.IN_PERSON_PARTICIPATION_DATE_LIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return EventEnrollment.EVENT_ENROLLMENT.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return EventEnrollment.EVENT_ENROLLMENT.LAST_UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getRegisteredUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIsLiveStream();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLiveStreamRegistrationTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getIsResidential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getResidentialRegistrationTs();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object component8() {
        return getInPersonParticipationDateList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getRegisteredUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIsLiveStream();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLiveStreamRegistrationTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIsResidential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getResidentialRegistrationTs();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object value8() {
        return getInPersonParticipationDateList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value3(Long value) {
        setRegisteredUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value4(String value) {
        setIsLiveStream(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value5(Timestamp value) {
        setLiveStreamRegistrationTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value6(String value) {
        setIsResidential(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value7(Timestamp value) {
        setResidentialRegistrationTs(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public EventEnrollmentRecord value8(Object value) {
        setInPersonParticipationDateList(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value9(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord value10(Timestamp value) {
        setLastUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventEnrollmentRecord values(Long value1, Long value2, Long value3, String value4, Timestamp value5, String value6, Timestamp value7, Object value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventEnrollmentRecord
     */
    public EventEnrollmentRecord() {
        super(EventEnrollment.EVENT_ENROLLMENT);
    }

    /**
     * Create a detached, initialised EventEnrollmentRecord
     */
    public EventEnrollmentRecord(Long id, Long eventId, Long registeredUserId, String isLiveStream, Timestamp liveStreamRegistrationTs, String isResidential, Timestamp residentialRegistrationTs, Object inPersonParticipationDateList, Timestamp createdOn, Timestamp lastUpdatedOn) {
        super(EventEnrollment.EVENT_ENROLLMENT);

        set(0, id);
        set(1, eventId);
        set(2, registeredUserId);
        set(3, isLiveStream);
        set(4, liveStreamRegistrationTs);
        set(5, isResidential);
        set(6, residentialRegistrationTs);
        set(7, inPersonParticipationDateList);
        set(8, createdOn);
        set(9, lastUpdatedOn);
    }
}
