/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import com.jakala.menarini.core.entities.EventSessionDate;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventSessionDateRecord extends UpdatableRecordImpl<EventSessionDateRecord> implements Record9<Long, String, Integer, Date, Long, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1196658396;

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.session</code>.
     */
    public void setSession(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.session</code>.
     */
    public String getSession() {
        return (String) get(1);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.seq_no</code>.
     */
    public void setSeqNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.seq_no</code>.
     */
    public Integer getSeqNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.session_date</code>.
     */
    public void setSessionDate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.session_date</code>.
     */
    public Date getSessionDate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.venue_id</code>.
     */
    public void setVenueId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.venue_id</code>.
     */
    public Long getVenueId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.event_id</code>.
     */
    public void setEventId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>menarini_dev.EVENT_SESSION_DATE.last_updated_on</code>.
     */
    public void setLastUpdatedOn(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT_SESSION_DATE.last_updated_on</code>.
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Integer, Date, Long, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Integer, Date, Long, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EventSessionDate.EVENT_SESSION_DATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EventSessionDate.EVENT_SESSION_DATE.SESSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EventSessionDate.EVENT_SESSION_DATE.SEQ_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return EventSessionDate.EVENT_SESSION_DATE.SESSION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return EventSessionDate.EVENT_SESSION_DATE.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return EventSessionDate.EVENT_SESSION_DATE.VENUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return EventSessionDate.EVENT_SESSION_DATE.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return EventSessionDate.EVENT_SESSION_DATE.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return EventSessionDate.EVENT_SESSION_DATE.LAST_UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSession();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getSeqNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getSessionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getVenueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSession();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSeqNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getSessionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getVenueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value2(String value) {
        setSession(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value3(Integer value) {
        setSeqNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value4(Date value) {
        setSessionDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value5(Long value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value6(Long value) {
        setVenueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value7(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value8(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord value9(Timestamp value) {
        setLastUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventSessionDateRecord values(Long value1, String value2, Integer value3, Date value4, Long value5, Long value6, Long value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventSessionDateRecord
     */
    public EventSessionDateRecord() {
        super(EventSessionDate.EVENT_SESSION_DATE);
    }

    /**
     * Create a detached, initialised EventSessionDateRecord
     */
    public EventSessionDateRecord(Long id, String session, Integer seqNo, Date sessionDate, Long locationId, Long venueId, Long eventId, Timestamp createdOn, Timestamp lastUpdatedOn) {
        super(EventSessionDate.EVENT_SESSION_DATE);

        set(0, id);
        set(1, session);
        set(2, seqNo);
        set(3, sessionDate);
        set(4, locationId);
        set(5, venueId);
        set(6, eventId);
        set(7, createdOn);
        set(8, lastUpdatedOn);
    }
}
