/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import com.jakala.menarini.core.entities.Event;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRecord extends UpdatableRecordImpl<EventRecord> implements Record12<Long, String, String, String, String, String, Date, Date, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1404496516;

    /**
     * Setter for <code>menarini_dev.EVENT.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.event_type</code>.
     */
    public void setEventType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.event_type</code>.
     */
    public String getEventType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.coordinators</code>.
     */
    public void setCoordinators(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.coordinators</code>.
     */
    public String getCoordinators() {
        return (String) get(4);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.subscription</code>.
     */
    public void setSubscription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.subscription</code>.
     */
    public String getSubscription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.start_date</code>.
     */
    public void setStartDate(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.start_date</code>.
     */
    public Date getStartDate() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.end_date</code>.
     */
    public void setEndDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.end_date</code>.
     */
    public Date getEndDate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.venue_id</code>.
     */
    public void setVenueId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.venue_id</code>.
     */
    public Long getVenueId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>menarini_dev.EVENT.last_updated_on</code>.
     */
    public void setLastUpdatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>menarini_dev.EVENT.last_updated_on</code>.
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Date, Date, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Date, Date, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Event.EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Event.EVENT.EVENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Event.EVENT.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Event.EVENT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Event.EVENT.COORDINATORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Event.EVENT.SUBSCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return Event.EVENT.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return Event.EVENT.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Event.EVENT.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Event.EVENT.VENUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Event.EVENT.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Event.EVENT.LAST_UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCoordinators();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSubscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component7() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getVenueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCoordinators();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSubscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getVenueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value2(String value) {
        setEventType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value5(String value) {
        setCoordinators(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value6(String value) {
        setSubscription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value7(Date value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value8(Date value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value9(Long value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value10(Long value) {
        setVenueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value11(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value12(Timestamp value) {
        setLastUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Date value7, Date value8, Long value9, Long value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventRecord
     */
    public EventRecord() {
        super(Event.EVENT);
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(Long id, String eventType, String title, String description, String coordinators, String subscription, Date startDate, Date endDate, Long locationId, Long venueId, Timestamp createdOn, Timestamp lastUpdatedOn) {
        super(Event.EVENT);

        set(0, id);
        set(1, eventType);
        set(2, title);
        set(3, description);
        set(4, coordinators);
        set(5, subscription);
        set(6, startDate);
        set(7, endDate);
        set(8, locationId);
        set(9, venueId);
        set(10, createdOn);
        set(11, lastUpdatedOn);
    }
}
