/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.time.LocalDateTime;

import com.jakala.menarini.core.entities.MagazineSubscription;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MagazineSubscriptionRecord extends UpdatableRecordImpl<MagazineSubscriptionRecord> implements Record22<Long, String, String, Long, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.magazine</code>.
     */
    public void setMagazine(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.magazine</code>.
     */
    public String getMagazine() {
        return (String) get(1);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.language</code>.
     */
    public void setLanguage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.language</code>.
     */
    public String getLanguage() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.registered_user_id</code>.
     */
    public void setRegisteredUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.registered_user_id</code>.
     */
    public Long getRegisteredUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.lastname</code>.
     */
    public void setLastname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.lastname</code>.
     */
    public String getLastname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.firstname</code>.
     */
    public void setFirstname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.address1</code>.
     */
    public void setAddress1(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.address1</code>.
     */
    public String getAddress1() {
        return (String) get(6);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.address2</code>.
     */
    public void setAddress2(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.address2</code>.
     */
    public String getAddress2() {
        return (String) get(7);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.house_no</code>.
     */
    public void setHouseNo(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.house_no</code>.
     */
    public String getHouseNo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.country</code>.
     */
    public void setCountry(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.country</code>.
     */
    public String getCountry() {
        return (String) get(9);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.province</code>.
     */
    public void setProvince(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.province</code>.
     */
    public String getProvince() {
        return (String) get(10);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.city</code>.
     */
    public void setCity(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.city</code>.
     */
    public String getCity() {
        return (String) get(11);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.zip</code>.
     */
    public void setZip(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.zip</code>.
     */
    public String getZip() {
        return (String) get(12);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.phone</code>.
     */
    public void setPhone(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.phone</code>.
     */
    public String getPhone() {
        return (String) get(13);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.tax_id_code</code>.
     */
    public void setTaxIdCode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.tax_id_code</code>.
     */
    public String getTaxIdCode() {
        return (String) get(14);
    }

    /**
     * Setter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.have_been_doctor_or_pharmacist</code>.
     */
    public void setHaveBeenDoctorOrPharmacist(String value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.have_been_doctor_or_pharmacist</code>.
     */
    public String getHaveBeenDoctorOrPharmacist() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.graduation_year</code>.
     */
    public void setGraduationYear(Integer value) {
        set(16, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.graduation_year</code>.
     */
    public Integer getGraduationYear() {
        return (Integer) get(16);
    }

    /**
     * Setter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.registration_year</code>.
     */
    public void setRegistrationYear(Integer value) {
        set(17, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.registration_year</code>.
     */
    public Integer getRegistrationYear() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.albo_province</code>.
     */
    public void setAlboProvince(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.albo_province</code>.
     */
    public String getAlboProvince() {
        return (String) get(18);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.albo_number</code>.
     */
    public void setAlboNumber(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.albo_number</code>.
     */
    public Integer getAlboNumber() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>menarini_dev.MAGAZINE_SUBSCRIPTION.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.last_updated_on</code>.
     */
    public void setLastUpdatedOn(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.MAGAZINE_SUBSCRIPTION.last_updated_on</code>.
     */
    public LocalDateTime getLastUpdatedOn() {
        return (LocalDateTime) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row22<Long, String, String, Long, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public Row22<Long, String, String, Long, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.ID;
    }

    @Override
    public Field<String> field2() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.MAGAZINE;
    }

    @Override
    public Field<String> field3() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.LANGUAGE;
    }

    @Override
    public Field<Long> field4() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.REGISTERED_USER_ID;
    }

    @Override
    public Field<String> field5() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.LASTNAME;
    }

    @Override
    public Field<String> field6() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.FIRSTNAME;
    }

    @Override
    public Field<String> field7() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.ADDRESS1;
    }

    @Override
    public Field<String> field8() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.ADDRESS2;
    }

    @Override
    public Field<String> field9() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.HOUSE_NO;
    }

    @Override
    public Field<String> field10() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.COUNTRY;
    }

    @Override
    public Field<String> field11() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.PROVINCE;
    }

    @Override
    public Field<String> field12() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.CITY;
    }

    @Override
    public Field<String> field13() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.ZIP;
    }

    @Override
    public Field<String> field14() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.PHONE;
    }

    @Override
    public Field<String> field15() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.TAX_ID_CODE;
    }

    @Override
    public Field<String> field16() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.HAVE_BEEN_DOCTOR_OR_PHARMACIST;
    }

    @Override
    public Field<Integer> field17() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.GRADUATION_YEAR;
    }

    @Override
    public Field<Integer> field18() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.REGISTRATION_YEAR;
    }

    @Override
    public Field<String> field19() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.ALBO_PROVINCE;
    }

    @Override
    public Field<Integer> field20() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.ALBO_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field21() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field22() {
        return MagazineSubscription.MAGAZINE_SUBSCRIPTION.LAST_UPDATED_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMagazine();
    }

    @Override
    public String component3() {
        return getLanguage();
    }

    @Override
    public Long component4() {
        return getRegisteredUserId();
    }

    @Override
    public String component5() {
        return getLastname();
    }

    @Override
    public String component6() {
        return getFirstname();
    }

    @Override
    public String component7() {
        return getAddress1();
    }

    @Override
    public String component8() {
        return getAddress2();
    }

    @Override
    public String component9() {
        return getHouseNo();
    }

    @Override
    public String component10() {
        return getCountry();
    }

    @Override
    public String component11() {
        return getProvince();
    }

    @Override
    public String component12() {
        return getCity();
    }

    @Override
    public String component13() {
        return getZip();
    }

    @Override
    public String component14() {
        return getPhone();
    }

    @Override
    public String component15() {
        return getTaxIdCode();
    }

    @Override
    public String component16() {
        return getHaveBeenDoctorOrPharmacist();
    }

    @Override
    public Integer component17() {
        return getGraduationYear();
    }

    @Override
    public Integer component18() {
        return getRegistrationYear();
    }

    @Override
    public String component19() {
        return getAlboProvince();
    }

    @Override
    public Integer component20() {
        return getAlboNumber();
    }

    @Override
    public LocalDateTime component21() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component22() {
        return getLastUpdatedOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMagazine();
    }

    @Override
    public String value3() {
        return getLanguage();
    }

    @Override
    public Long value4() {
        return getRegisteredUserId();
    }

    @Override
    public String value5() {
        return getLastname();
    }

    @Override
    public String value6() {
        return getFirstname();
    }

    @Override
    public String value7() {
        return getAddress1();
    }

    @Override
    public String value8() {
        return getAddress2();
    }

    @Override
    public String value9() {
        return getHouseNo();
    }

    @Override
    public String value10() {
        return getCountry();
    }

    @Override
    public String value11() {
        return getProvince();
    }

    @Override
    public String value12() {
        return getCity();
    }

    @Override
    public String value13() {
        return getZip();
    }

    @Override
    public String value14() {
        return getPhone();
    }

    @Override
    public String value15() {
        return getTaxIdCode();
    }

    @Override
    public String value16() {
        return getHaveBeenDoctorOrPharmacist();
    }

    @Override
    public Integer value17() {
        return getGraduationYear();
    }

    @Override
    public Integer value18() {
        return getRegistrationYear();
    }

    @Override
    public String value19() {
        return getAlboProvince();
    }

    @Override
    public Integer value20() {
        return getAlboNumber();
    }

    @Override
    public LocalDateTime value21() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value22() {
        return getLastUpdatedOn();
    }

    @Override
    public MagazineSubscriptionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value2(String value) {
        setMagazine(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value3(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value4(Long value) {
        setRegisteredUserId(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value5(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value6(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value7(String value) {
        setAddress1(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value8(String value) {
        setAddress2(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value9(String value) {
        setHouseNo(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value10(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value11(String value) {
        setProvince(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value12(String value) {
        setCity(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value13(String value) {
        setZip(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value14(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value15(String value) {
        setTaxIdCode(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value16(String value) {
        setHaveBeenDoctorOrPharmacist(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value17(Integer value) {
        setGraduationYear(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value18(Integer value) {
        setRegistrationYear(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value19(String value) {
        setAlboProvince(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value20(Integer value) {
        setAlboNumber(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value21(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord value22(LocalDateTime value) {
        setLastUpdatedOn(value);
        return this;
    }

    @Override
    public MagazineSubscriptionRecord values(Long value1, String value2, String value3, Long value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, Integer value17, Integer value18, String value19, Integer value20, LocalDateTime value21, LocalDateTime value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MagazineSubscriptionRecord
     */
    public MagazineSubscriptionRecord() {
        super(MagazineSubscription.MAGAZINE_SUBSCRIPTION);
    }

    /**
     * Create a detached, initialised MagazineSubscriptionRecord
     */
    public MagazineSubscriptionRecord(Long id, String magazine, String language, Long registeredUserId, String lastname, String firstname, String address1, String address2, String houseNo, String country, String province, String city, String zip, String phone, String taxIdCode, String haveBeenDoctorOrPharmacist, Integer graduationYear, Integer registrationYear, String alboProvince, Integer alboNumber, LocalDateTime createdOn, LocalDateTime lastUpdatedOn) {
        super(MagazineSubscription.MAGAZINE_SUBSCRIPTION);

        setId(id);
        setMagazine(magazine);
        setLanguage(language);
        setRegisteredUserId(registeredUserId);
        setLastname(lastname);
        setFirstname(firstname);
        setAddress1(address1);
        setAddress2(address2);
        setHouseNo(houseNo);
        setCountry(country);
        setProvince(province);
        setCity(city);
        setZip(zip);
        setPhone(phone);
        setTaxIdCode(taxIdCode);
        setHaveBeenDoctorOrPharmacist(haveBeenDoctorOrPharmacist);
        setGraduationYear(graduationYear);
        setRegistrationYear(registrationYear);
        setAlboProvince(alboProvince);
        setAlboNumber(alboNumber);
        setCreatedOn(createdOn);
        setLastUpdatedOn(lastUpdatedOn);
    }
}
