/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import com.jakala.menarini.core.entities.NewsletterSubscription;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsletterSubscriptionRecord extends UpdatableRecordImpl<NewsletterSubscriptionRecord> implements Record12<Long, String, String, String, String, String, Timestamp, String, Timestamp, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1456705868;

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.lastname</code>.
     */
    public void setLastname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.lastname</code>.
     */
    public String getLastname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.firstname</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.occupation</code>.
     */
    public void setOccupation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.occupation</code>.
     */
    public String getOccupation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.personal_data_processing_consent</code>.
     */
    public void setPersonalDataProcessingConsent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.personal_data_processing_consent</code>.
     */
    public String getPersonalDataProcessingConsent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.personal_data_processing_consent_ts</code>.
     */
    public void setPersonalDataProcessingConsentTs(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.personal_data_processing_consent_ts</code>.
     */
    public Timestamp getPersonalDataProcessingConsentTs() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.newsletter_subscription</code>.
     */
    public void setNewsletterSubscription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.newsletter_subscription</code>.
     */
    public String getNewsletterSubscription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.newsletter_subscription_ts</code>.
     */
    public void setNewsletterSubscriptionTs(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.newsletter_subscription_ts</code>.
     */
    public Timestamp getNewsletterSubscriptionTs() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.registered_user_id</code>.
     */
    public void setRegisteredUserId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.registered_user_id</code>.
     */
    public Long getRegisteredUserId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.last_updated_on</code>.
     */
    public void setLastUpdatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>menarini_dev.NEWSLETTER_SUBSCRIPTION.last_updated_on</code>.
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Timestamp, String, Timestamp, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Timestamp, String, Timestamp, Long, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.OCCUPATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.PERSONAL_DATA_PROCESSING_CONSENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.PERSONAL_DATA_PROCESSING_CONSENT_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.NEWSLETTER_SUBSCRIPTION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.NEWSLETTER_SUBSCRIPTION_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.REGISTERED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.LAST_UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOccupation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPersonalDataProcessingConsent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getPersonalDataProcessingConsentTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNewsletterSubscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getNewsletterSubscriptionTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getRegisteredUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOccupation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPersonalDataProcessingConsent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getPersonalDataProcessingConsentTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNewsletterSubscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getNewsletterSubscriptionTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getRegisteredUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value2(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value5(String value) {
        setOccupation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value6(String value) {
        setPersonalDataProcessingConsent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value7(Timestamp value) {
        setPersonalDataProcessingConsentTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value8(String value) {
        setNewsletterSubscription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value9(Timestamp value) {
        setNewsletterSubscriptionTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value10(Long value) {
        setRegisteredUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value11(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord value12(Timestamp value) {
        setLastUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsletterSubscriptionRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, String value8, Timestamp value9, Long value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NewsletterSubscriptionRecord
     */
    public NewsletterSubscriptionRecord() {
        super(NewsletterSubscription.NEWSLETTER_SUBSCRIPTION);
    }

    /**
     * Create a detached, initialised NewsletterSubscriptionRecord
     */
    public NewsletterSubscriptionRecord(Long id, String lastname, String firstname, String email, String occupation, String personalDataProcessingConsent, Timestamp personalDataProcessingConsentTs, String newsletterSubscription, Timestamp newsletterSubscriptionTs, Long registeredUserId, Timestamp createdOn, Timestamp lastUpdatedOn) {
        super(NewsletterSubscription.NEWSLETTER_SUBSCRIPTION);

        set(0, id);
        set(1, lastname);
        set(2, firstname);
        set(3, email);
        set(4, occupation);
        set(5, personalDataProcessingConsent);
        set(6, personalDataProcessingConsentTs);
        set(7, newsletterSubscription);
        set(8, newsletterSubscriptionTs);
        set(9, registeredUserId);
        set(10, createdOn);
        set(11, lastUpdatedOn);
    }
}
