/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import com.jakala.menarini.core.entities.RegisteredUserRole;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisteredUserRoleRecord extends UpdatableRecordImpl<RegisteredUserRoleRecord> implements Record5<Long, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1825582135;

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_ROLE.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_ROLE.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_ROLE.registered_user_id</code>.
     */
    public void setRegisteredUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_ROLE.registered_user_id</code>.
     */
    public Long getRegisteredUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_ROLE.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_ROLE.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_ROLE.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_ROLE.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_ROLE.last_updated_on</code>.
     */
    public void setLastUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_ROLE.last_updated_on</code>.
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.REGISTERED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.LAST_UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getRegisteredUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRegisteredUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRoleRecord value2(Long value) {
        setRegisteredUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRoleRecord value3(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRoleRecord value4(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRoleRecord value5(Timestamp value) {
        setLastUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRoleRecord values(Long value1, Long value2, Long value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisteredUserRoleRecord
     */
    public RegisteredUserRoleRecord() {
        super(RegisteredUserRole.REGISTERED_USER_ROLE);
    }

    /**
     * Create a detached, initialised RegisteredUserRoleRecord
     */
    public RegisteredUserRoleRecord(Long id, Long registeredUserId, Long roleId, Timestamp createdOn, Timestamp lastUpdatedOn) {
        super(RegisteredUserRole.REGISTERED_USER_ROLE);

        set(0, id);
        set(1, registeredUserId);
        set(2, roleId);
        set(3, createdOn);
        set(4, lastUpdatedOn);
    }
}
