/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import com.jakala.menarini.core.entities.RegisteredUserTopic;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisteredUserTopicRecord extends UpdatableRecordImpl<RegisteredUserTopicRecord> implements Record6<Long, Integer, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = 140697356;

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.seq_no</code>.
     */
    public void setSeqNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.seq_no</code>.
     */
    public Integer getSeqNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.topic_id</code>.
     */
    public void setTopicId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.topic_id</code>.
     */
    public Long getTopicId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.registered_user_id</code>.
     */
    public void setRegisteredUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.registered_user_id</code>.
     */
    public Long getRegisteredUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.last_updated_on</code>.
     */
    public void setLastUpdatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.last_updated_on</code>.
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Integer, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Integer, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.SEQ_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.TOPIC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.REGISTERED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.LAST_UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSeqNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getRegisteredUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSeqNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getRegisteredUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserTopicRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserTopicRecord value2(Integer value) {
        setSeqNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserTopicRecord value3(Long value) {
        setTopicId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserTopicRecord value4(Long value) {
        setRegisteredUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserTopicRecord value5(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserTopicRecord value6(Timestamp value) {
        setLastUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserTopicRecord values(Long value1, Integer value2, Long value3, Long value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisteredUserTopicRecord
     */
    public RegisteredUserTopicRecord() {
        super(RegisteredUserTopic.REGISTERED_USER_TOPIC);
    }

    /**
     * Create a detached, initialised RegisteredUserTopicRecord
     */
    public RegisteredUserTopicRecord(Long id, Integer seqNo, Long topicId, Long registeredUserId, Timestamp createdOn, Timestamp lastUpdatedOn) {
        super(RegisteredUserTopic.REGISTERED_USER_TOPIC);

        set(0, id);
        set(1, seqNo);
        set(2, topicId);
        set(3, registeredUserId);
        set(4, createdOn);
        set(5, lastUpdatedOn);
    }
}
