/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.time.LocalDateTime;

import com.jakala.menarini.core.entities.RegisteredUserRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisteredUserRoleRecord extends UpdatableRecordImpl<RegisteredUserRoleRecord> implements Record5<Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_ROLE.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_ROLE.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER_ROLE.registered_user_id</code>.
     */
    public void setRegisteredUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER_ROLE.registered_user_id</code>.
     */
    public Long getRegisteredUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_ROLE.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_ROLE.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_ROLE.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_ROLE.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER_ROLE.last_updated_on</code>.
     */
    public void setLastUpdatedOn(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER_ROLE.last_updated_on</code>.
     */
    public LocalDateTime getLastUpdatedOn() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.ID;
    }

    @Override
    public Field<Long> field2() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.REGISTERED_USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.ROLE_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return RegisteredUserRole.REGISTERED_USER_ROLE.LAST_UPDATED_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getRegisteredUserId();
    }

    @Override
    public Long component3() {
        return getRoleId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component5() {
        return getLastUpdatedOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getRegisteredUserId();
    }

    @Override
    public Long value3() {
        return getRoleId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value5() {
        return getLastUpdatedOn();
    }

    @Override
    public RegisteredUserRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RegisteredUserRoleRecord value2(Long value) {
        setRegisteredUserId(value);
        return this;
    }

    @Override
    public RegisteredUserRoleRecord value3(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RegisteredUserRoleRecord value4(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public RegisteredUserRoleRecord value5(LocalDateTime value) {
        setLastUpdatedOn(value);
        return this;
    }

    @Override
    public RegisteredUserRoleRecord values(Long value1, Long value2, Long value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisteredUserRoleRecord
     */
    public RegisteredUserRoleRecord() {
        super(RegisteredUserRole.REGISTERED_USER_ROLE);
    }

    /**
     * Create a detached, initialised RegisteredUserRoleRecord
     */
    public RegisteredUserRoleRecord(Long id, Long registeredUserId, Long roleId, LocalDateTime createdOn, LocalDateTime lastUpdatedOn) {
        super(RegisteredUserRole.REGISTERED_USER_ROLE);

        setId(id);
        setRegisteredUserId(registeredUserId);
        setRoleId(roleId);
        setCreatedOn(createdOn);
        setLastUpdatedOn(lastUpdatedOn);
    }
}
