/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import com.jakala.menarini.core.entities.RegisteredUser;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisteredUserRecord extends UpdatableRecordImpl<RegisteredUserRecord> implements Record21<Long, String, String, String, String, String, String, Date, String, String, String, String, String, Timestamp, String, Timestamp, String, Timestamp, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -395265299;

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.lastname</code>.
     */
    public void setLastname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.lastname</code>.
     */
    public String getLastname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.firstname</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.occupation</code>.
     */
    public void setOccupation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.occupation</code>.
     */
    public String getOccupation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.gender</code>.
     */
    public void setGender(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.gender</code>.
     */
    public String getGender() {
        return (String) get(6);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.birth_date</code>.
     */
    public void setBirthDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.birth_date</code>.
     */
    public Date getBirthDate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.phone</code>.
     */
    public void setPhone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.phone</code>.
     */
    public String getPhone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.tax_id_code</code>.
     */
    public void setTaxIdCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.tax_id_code</code>.
     */
    public String getTaxIdCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.linkedin_profile</code>.
     */
    public void setLinkedinProfile(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.linkedin_profile</code>.
     */
    public String getLinkedinProfile() {
        return (String) get(10);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.country</code>.
     */
    public void setCountry(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.country</code>.
     */
    public String getCountry() {
        return (String) get(11);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.personal_data_processing_consent</code>.
     */
    public void setPersonalDataProcessingConsent(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.personal_data_processing_consent</code>.
     */
    public String getPersonalDataProcessingConsent() {
        return (String) get(12);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.personal_data_processing_consent_ts</code>.
     */
    public void setPersonalDataProcessingConsentTs(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.personal_data_processing_consent_ts</code>.
     */
    public Timestamp getPersonalDataProcessingConsentTs() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.profiling_consent</code>.
     */
    public void setProfilingConsent(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.profiling_consent</code>.
     */
    public String getProfilingConsent() {
        return (String) get(14);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.profiling_consent_ts</code>.
     */
    public void setProfilingConsentTs(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.profiling_consent_ts</code>.
     */
    public Timestamp getProfilingConsentTs() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.newsletter_subscription</code>.
     */
    public void setNewsletterSubscription(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.newsletter_subscription</code>.
     */
    public String getNewsletterSubscription() {
        return (String) get(16);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.newsletter_subscription_ts</code>.
     */
    public void setNewsletterSubscriptionTs(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.newsletter_subscription_ts</code>.
     */
    public Timestamp getNewsletterSubscriptionTs() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.legacy_id</code>.
     */
    public void setLegacyId(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.legacy_id</code>.
     */
    public Integer getLegacyId() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(19, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(19);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.last_updated_on</code>.
     */
    public void setLastUpdatedOn(Timestamp value) {
        set(20, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.last_updated_on</code>.
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, String, String, String, String, String, String, Date, String, String, String, String, String, Timestamp, String, Timestamp, String, Timestamp, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, String, String, String, String, String, String, Date, String, String, String, String, String, Timestamp, String, Timestamp, String, Timestamp, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RegisteredUser.REGISTERED_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RegisteredUser.REGISTERED_USER.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RegisteredUser.REGISTERED_USER.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RegisteredUser.REGISTERED_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RegisteredUser.REGISTERED_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return RegisteredUser.REGISTERED_USER.OCCUPATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return RegisteredUser.REGISTERED_USER.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return RegisteredUser.REGISTERED_USER.BIRTH_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return RegisteredUser.REGISTERED_USER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return RegisteredUser.REGISTERED_USER.TAX_ID_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return RegisteredUser.REGISTERED_USER.LINKEDIN_PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return RegisteredUser.REGISTERED_USER.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return RegisteredUser.REGISTERED_USER.PERSONAL_DATA_PROCESSING_CONSENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return RegisteredUser.REGISTERED_USER.PERSONAL_DATA_PROCESSING_CONSENT_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return RegisteredUser.REGISTERED_USER.PROFILING_CONSENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return RegisteredUser.REGISTERED_USER.PROFILING_CONSENT_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return RegisteredUser.REGISTERED_USER.NEWSLETTER_SUBSCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return RegisteredUser.REGISTERED_USER.NEWSLETTER_SUBSCRIPTION_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field19() {
        return RegisteredUser.REGISTERED_USER.LEGACY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field20() {
        return RegisteredUser.REGISTERED_USER.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field21() {
        return RegisteredUser.REGISTERED_USER.LAST_UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getOccupation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getTaxIdCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getLinkedinProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getPersonalDataProcessingConsent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getPersonalDataProcessingConsentTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getProfilingConsent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getProfilingConsentTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getNewsletterSubscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getNewsletterSubscriptionTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component19() {
        return getLegacyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component20() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component21() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOccupation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getTaxIdCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getLinkedinProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPersonalDataProcessingConsent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getPersonalDataProcessingConsentTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getProfilingConsent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getProfilingConsentTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getNewsletterSubscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getNewsletterSubscriptionTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value19() {
        return getLegacyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value20() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value21() {
        return getLastUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value2(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value6(String value) {
        setOccupation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value7(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value8(Date value) {
        setBirthDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value9(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value10(String value) {
        setTaxIdCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value11(String value) {
        setLinkedinProfile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value12(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value13(String value) {
        setPersonalDataProcessingConsent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value14(Timestamp value) {
        setPersonalDataProcessingConsentTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value15(String value) {
        setProfilingConsent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value16(Timestamp value) {
        setProfilingConsentTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value17(String value) {
        setNewsletterSubscription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value18(Timestamp value) {
        setNewsletterSubscriptionTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value19(Integer value) {
        setLegacyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value20(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord value21(Timestamp value) {
        setLastUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisteredUserRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Date value8, String value9, String value10, String value11, String value12, String value13, Timestamp value14, String value15, Timestamp value16, String value17, Timestamp value18, Integer value19, Timestamp value20, Timestamp value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisteredUserRecord
     */
    public RegisteredUserRecord() {
        super(RegisteredUser.REGISTERED_USER);
    }

    /**
     * Create a detached, initialised RegisteredUserRecord
     */
    public RegisteredUserRecord(Long id, String lastname, String firstname, String email, String username, String occupation, String gender, Date birthDate, String phone, String taxIdCode, String linkedinProfile, String country, String personalDataProcessingConsent, Timestamp personalDataProcessingConsentTs, String profilingConsent, Timestamp profilingConsentTs, String newsletterSubscription, Timestamp newsletterSubscriptionTs, Integer legacyId, Timestamp createdOn, Timestamp lastUpdatedOn) {
        super(RegisteredUser.REGISTERED_USER);

        set(0, id);
        set(1, lastname);
        set(2, firstname);
        set(3, email);
        set(4, username);
        set(5, occupation);
        set(6, gender);
        set(7, birthDate);
        set(8, phone);
        set(9, taxIdCode);
        set(10, linkedinProfile);
        set(11, country);
        set(12, personalDataProcessingConsent);
        set(13, personalDataProcessingConsentTs);
        set(14, profilingConsent);
        set(15, profilingConsentTs);
        set(16, newsletterSubscription);
        set(17, newsletterSubscriptionTs);
        set(18, legacyId);
        set(19, createdOn);
        set(20, lastUpdatedOn);
    }
}
