/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.time.LocalDateTime;

import com.jakala.menarini.core.entities.RegisteredUserTopic;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisteredUserTopicRecord extends UpdatableRecordImpl<RegisteredUserTopicRecord> implements Record6<Long, Integer, String, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.seq_no</code>.
     */
    public void setSeqNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.seq_no</code>.
     */
    public Integer getSeqNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.topic_id</code>.
     */
    public void setTopicId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.topic_id</code>.
     */
    public String getTopicId() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER_TOPIC.registered_user_id</code>.
     */
    public void setRegisteredUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER_TOPIC.registered_user_id</code>.
     */
    public Long getRegisteredUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER_TOPIC.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER_TOPIC.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER_TOPIC.last_updated_on</code>.
     */
    public void setLastUpdatedOn(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER_TOPIC.last_updated_on</code>.
     */
    public LocalDateTime getLastUpdatedOn() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Integer, String, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Integer, String, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.ID;
    }

    @Override
    public Field<Integer> field2() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.SEQ_NO;
    }

    @Override
    public Field<String> field3() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.TOPIC_ID;
    }

    @Override
    public Field<Long> field4() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.REGISTERED_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return RegisteredUserTopic.REGISTERED_USER_TOPIC.LAST_UPDATED_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSeqNo();
    }

    @Override
    public String component3() {
        return getTopicId();
    }

    @Override
    public Long component4() {
        return getRegisteredUserId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component6() {
        return getLastUpdatedOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSeqNo();
    }

    @Override
    public String value3() {
        return getTopicId();
    }

    @Override
    public Long value4() {
        return getRegisteredUserId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value6() {
        return getLastUpdatedOn();
    }

    @Override
    public RegisteredUserTopicRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RegisteredUserTopicRecord value2(Integer value) {
        setSeqNo(value);
        return this;
    }

    @Override
    public RegisteredUserTopicRecord value3(String value) {
        setTopicId(value);
        return this;
    }

    @Override
    public RegisteredUserTopicRecord value4(Long value) {
        setRegisteredUserId(value);
        return this;
    }

    @Override
    public RegisteredUserTopicRecord value5(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public RegisteredUserTopicRecord value6(LocalDateTime value) {
        setLastUpdatedOn(value);
        return this;
    }

    @Override
    public RegisteredUserTopicRecord values(Long value1, Integer value2, String value3, Long value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisteredUserTopicRecord
     */
    public RegisteredUserTopicRecord() {
        super(RegisteredUserTopic.REGISTERED_USER_TOPIC);
    }

    /**
     * Create a detached, initialised RegisteredUserTopicRecord
     */
    public RegisteredUserTopicRecord(Long id, Integer seqNo, String topicId, Long registeredUserId, LocalDateTime createdOn, LocalDateTime lastUpdatedOn) {
        super(RegisteredUserTopic.REGISTERED_USER_TOPIC);

        setId(id);
        setSeqNo(seqNo);
        setTopicId(topicId);
        setRegisteredUserId(registeredUserId);
        setCreatedOn(createdOn);
        setLastUpdatedOn(lastUpdatedOn);
    }
}
