/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import com.jakala.menarini.core.entities.RegisteredUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisteredUserRecord extends UpdatableRecordImpl<RegisteredUserRecord> implements Record22<Long, String, String, String, String, String, String, LocalDate, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, LocalDateTime, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.lastname</code>.
     */
    public void setLastname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.lastname</code>.
     */
    public String getLastname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.firstname</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.occupation</code>.
     */
    public void setOccupation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.occupation</code>.
     */
    public String getOccupation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.gender</code>.
     */
    public void setGender(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.gender</code>.
     */
    public String getGender() {
        return (String) get(6);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.birth_date</code>.
     */
    public void setBirthDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.phone</code>.
     */
    public void setPhone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.phone</code>.
     */
    public String getPhone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.tax_id_code</code>.
     */
    public void setTaxIdCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.tax_id_code</code>.
     */
    public String getTaxIdCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.linkedin_profile</code>.
     */
    public void setLinkedinProfile(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.linkedin_profile</code>.
     */
    public String getLinkedinProfile() {
        return (String) get(10);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.country</code>.
     */
    public void setCountry(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.country</code>.
     */
    public String getCountry() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER.personal_data_processing_consent</code>.
     */
    public void setPersonalDataProcessingConsent(String value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER.personal_data_processing_consent</code>.
     */
    public String getPersonalDataProcessingConsent() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER.personal_data_processing_consent_ts</code>.
     */
    public void setPersonalDataProcessingConsentTs(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER.personal_data_processing_consent_ts</code>.
     */
    public LocalDateTime getPersonalDataProcessingConsentTs() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.profiling_consent</code>.
     */
    public void setProfilingConsent(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.profiling_consent</code>.
     */
    public String getProfilingConsent() {
        return (String) get(14);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER.profiling_consent_ts</code>.
     */
    public void setProfilingConsentTs(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER.profiling_consent_ts</code>.
     */
    public LocalDateTime getProfilingConsentTs() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER.newsletter_subscription</code>.
     */
    public void setNewsletterSubscription(String value) {
        set(16, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER.newsletter_subscription</code>.
     */
    public String getNewsletterSubscription() {
        return (String) get(16);
    }

    /**
     * Setter for
     * <code>menarini_dev.REGISTERED_USER.newsletter_subscription_ts</code>.
     */
    public void setNewsletterSubscriptionTs(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for
     * <code>menarini_dev.REGISTERED_USER.newsletter_subscription_ts</code>.
     */
    public LocalDateTime getNewsletterSubscriptionTs() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.legacy_id</code>.
     */
    public void setLegacyId(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.legacy_id</code>.
     */
    public Integer getLegacyId() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.registration_status</code>.
     */
    public void setRegistrationStatus(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.registration_status</code>.
     */
    public String getRegistrationStatus() {
        return (String) get(19);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>menarini_dev.REGISTERED_USER.last_updated_on</code>.
     */
    public void setLastUpdatedOn(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>menarini_dev.REGISTERED_USER.last_updated_on</code>.
     */
    public LocalDateTime getLastUpdatedOn() {
        return (LocalDateTime) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row22<Long, String, String, String, String, String, String, LocalDate, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, LocalDateTime, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public Row22<Long, String, String, String, String, String, String, LocalDate, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, LocalDateTime, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RegisteredUser.REGISTERED_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return RegisteredUser.REGISTERED_USER.LASTNAME;
    }

    @Override
    public Field<String> field3() {
        return RegisteredUser.REGISTERED_USER.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return RegisteredUser.REGISTERED_USER.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return RegisteredUser.REGISTERED_USER.USERNAME;
    }

    @Override
    public Field<String> field6() {
        return RegisteredUser.REGISTERED_USER.OCCUPATION;
    }

    @Override
    public Field<String> field7() {
        return RegisteredUser.REGISTERED_USER.GENDER;
    }

    @Override
    public Field<LocalDate> field8() {
        return RegisteredUser.REGISTERED_USER.BIRTH_DATE;
    }

    @Override
    public Field<String> field9() {
        return RegisteredUser.REGISTERED_USER.PHONE;
    }

    @Override
    public Field<String> field10() {
        return RegisteredUser.REGISTERED_USER.TAX_ID_CODE;
    }

    @Override
    public Field<String> field11() {
        return RegisteredUser.REGISTERED_USER.LINKEDIN_PROFILE;
    }

    @Override
    public Field<String> field12() {
        return RegisteredUser.REGISTERED_USER.COUNTRY;
    }

    @Override
    public Field<String> field13() {
        return RegisteredUser.REGISTERED_USER.PERSONAL_DATA_PROCESSING_CONSENT;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return RegisteredUser.REGISTERED_USER.PERSONAL_DATA_PROCESSING_CONSENT_TS;
    }

    @Override
    public Field<String> field15() {
        return RegisteredUser.REGISTERED_USER.PROFILING_CONSENT;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return RegisteredUser.REGISTERED_USER.PROFILING_CONSENT_TS;
    }

    @Override
    public Field<String> field17() {
        return RegisteredUser.REGISTERED_USER.NEWSLETTER_SUBSCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return RegisteredUser.REGISTERED_USER.NEWSLETTER_SUBSCRIPTION_TS;
    }

    @Override
    public Field<Integer> field19() {
        return RegisteredUser.REGISTERED_USER.LEGACY_ID;
    }

    @Override
    public Field<String> field20() {
        return RegisteredUser.REGISTERED_USER.REGISTRATION_STATUS;
    }

    @Override
    public Field<LocalDateTime> field21() {
        return RegisteredUser.REGISTERED_USER.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field22() {
        return RegisteredUser.REGISTERED_USER.LAST_UPDATED_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLastname();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getUsername();
    }

    @Override
    public String component6() {
        return getOccupation();
    }

    @Override
    public String component7() {
        return getGender();
    }

    @Override
    public LocalDate component8() {
        return getBirthDate();
    }

    @Override
    public String component9() {
        return getPhone();
    }

    @Override
    public String component10() {
        return getTaxIdCode();
    }

    @Override
    public String component11() {
        return getLinkedinProfile();
    }

    @Override
    public String component12() {
        return getCountry();
    }

    @Override
    public String component13() {
        return getPersonalDataProcessingConsent();
    }

    @Override
    public LocalDateTime component14() {
        return getPersonalDataProcessingConsentTs();
    }

    @Override
    public String component15() {
        return getProfilingConsent();
    }

    @Override
    public LocalDateTime component16() {
        return getProfilingConsentTs();
    }

    @Override
    public String component17() {
        return getNewsletterSubscription();
    }

    @Override
    public LocalDateTime component18() {
        return getNewsletterSubscriptionTs();
    }

    @Override
    public Integer component19() {
        return getLegacyId();
    }

    @Override
    public String component20() {
        return getRegistrationStatus();
    }

    @Override
    public LocalDateTime component21() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component22() {
        return getLastUpdatedOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLastname();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getUsername();
    }

    @Override
    public String value6() {
        return getOccupation();
    }

    @Override
    public String value7() {
        return getGender();
    }

    @Override
    public LocalDate value8() {
        return getBirthDate();
    }

    @Override
    public String value9() {
        return getPhone();
    }

    @Override
    public String value10() {
        return getTaxIdCode();
    }

    @Override
    public String value11() {
        return getLinkedinProfile();
    }

    @Override
    public String value12() {
        return getCountry();
    }

    @Override
    public String value13() {
        return getPersonalDataProcessingConsent();
    }

    @Override
    public LocalDateTime value14() {
        return getPersonalDataProcessingConsentTs();
    }

    @Override
    public String value15() {
        return getProfilingConsent();
    }

    @Override
    public LocalDateTime value16() {
        return getProfilingConsentTs();
    }

    @Override
    public String value17() {
        return getNewsletterSubscription();
    }

    @Override
    public LocalDateTime value18() {
        return getNewsletterSubscriptionTs();
    }

    @Override
    public Integer value19() {
        return getLegacyId();
    }

    @Override
    public String value20() {
        return getRegistrationStatus();
    }

    @Override
    public LocalDateTime value21() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value22() {
        return getLastUpdatedOn();
    }

    @Override
    public RegisteredUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value2(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value5(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value6(String value) {
        setOccupation(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value7(String value) {
        setGender(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value8(LocalDate value) {
        setBirthDate(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value9(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value10(String value) {
        setTaxIdCode(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value11(String value) {
        setLinkedinProfile(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value12(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value13(String value) {
        setPersonalDataProcessingConsent(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value14(LocalDateTime value) {
        setPersonalDataProcessingConsentTs(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value15(String value) {
        setProfilingConsent(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value16(LocalDateTime value) {
        setProfilingConsentTs(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value17(String value) {
        setNewsletterSubscription(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value18(LocalDateTime value) {
        setNewsletterSubscriptionTs(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value19(Integer value) {
        setLegacyId(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value20(String value) {
        setRegistrationStatus(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value21(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public RegisteredUserRecord value22(LocalDateTime value) {
        setLastUpdatedOn(value);
        return this;
    }

    @Override
    public RegisteredUserRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, LocalDate value8, String value9, String value10, String value11, String value12, String value13, LocalDateTime value14, String value15, LocalDateTime value16, String value17, LocalDateTime value18, Integer value19, String value20, LocalDateTime value21, LocalDateTime value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisteredUserRecord
     */
    public RegisteredUserRecord() {
        super(RegisteredUser.REGISTERED_USER);
    }

    /**
     * Create a detached, initialised RegisteredUserRecord
     */
    public RegisteredUserRecord(Long id, String lastname, String firstname, String email, String username, String occupation, String gender, LocalDate birthDate, String phone, String taxIdCode, String linkedinProfile, String country, String personalDataProcessingConsent, LocalDateTime personalDataProcessingConsentTs, String profilingConsent, LocalDateTime profilingConsentTs, String newsletterSubscription, LocalDateTime newsletterSubscriptionTs, Integer legacyId, String registrationStatus, LocalDateTime createdOn, LocalDateTime lastUpdatedOn) {
        super(RegisteredUser.REGISTERED_USER);

        setId(id);
        setLastname(lastname);
        setFirstname(firstname);
        setEmail(email);
        setUsername(username);
        setOccupation(occupation);
        setGender(gender);
        setBirthDate(birthDate);
        setPhone(phone);
        setTaxIdCode(taxIdCode);
        setLinkedinProfile(linkedinProfile);
        setCountry(country);
        setPersonalDataProcessingConsent(personalDataProcessingConsent);
        setPersonalDataProcessingConsentTs(personalDataProcessingConsentTs);
        setProfilingConsent(profilingConsent);
        setProfilingConsentTs(profilingConsentTs);
        setNewsletterSubscription(newsletterSubscription);
        setNewsletterSubscriptionTs(newsletterSubscriptionTs);
        setLegacyId(legacyId);
        setRegistrationStatus(registrationStatus);
        setCreatedOn(createdOn);
        setLastUpdatedOn(lastUpdatedOn);
    }
}
