/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.records;


import java.time.LocalDateTime;

import com.jakala.menarini.core.entities.Topic;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TopicRecord extends UpdatableRecordImpl<TopicRecord> implements Record4<Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>menarini_dev.TOPIC.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>menarini_dev.TOPIC.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>menarini_dev.TOPIC.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>menarini_dev.TOPIC.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>menarini_dev.TOPIC.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>menarini_dev.TOPIC.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>menarini_dev.TOPIC.last_updated_on</code>.
     */
    public void setLastUpdatedOn(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>menarini_dev.TOPIC.last_updated_on</code>.
     */
    public LocalDateTime getLastUpdatedOn() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Topic.TOPIC.ID;
    }

    @Override
    public Field<String> field2() {
        return Topic.TOPIC.NAME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Topic.TOPIC.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Topic.TOPIC.LAST_UPDATED_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdatedOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdatedOn();
    }

    @Override
    public TopicRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TopicRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TopicRecord value3(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public TopicRecord value4(LocalDateTime value) {
        setLastUpdatedOn(value);
        return this;
    }

    @Override
    public TopicRecord values(Long value1, String value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopicRecord
     */
    public TopicRecord() {
        super(Topic.TOPIC);
    }

    /**
     * Create a detached, initialised TopicRecord
     */
    public TopicRecord(Long id, String name, LocalDateTime createdOn, LocalDateTime lastUpdatedOn) {
        super(Topic.TOPIC);

        setId(id);
        setName(name);
        setCreatedOn(createdOn);
        setLastUpdatedOn(lastUpdatedOn);
    }
}
