/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.utils;


import java.util.Arrays;
import java.util.List;

import com.jakala.menarini.core.entities.EventEnrollment;
import com.jakala.menarini.core.entities.RegisteredUser;
import com.jakala.menarini.core.entities.RegisteredUserRole;
import com.jakala.menarini.core.entities.RegisteredUserTopic;
import com.jakala.menarini.core.entities.Role;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>menarini_dev</code>
     */
    public static final DbSchema MENARINI = new DbSchema();

    /**
     * The table <code>menarini_dev.EVENT_ENROLLMENT</code>.
     */
    public final EventEnrollment EVENT_ENROLLMENT = EventEnrollment.EVENT_ENROLLMENT;

    /**
     * The table <code>menarini_dev.REGISTERED_USER</code>.
     */
    public final RegisteredUser REGISTERED_USER = RegisteredUser.REGISTERED_USER;

    /**
     * The table <code>menarini_dev.REGISTERED_USER_ROLE</code>.
     */
    public final RegisteredUserRole REGISTERED_USER_ROLE = RegisteredUserRole.REGISTERED_USER_ROLE;

    /**
     * The table <code>menarini_dev.REGISTERED_USER_TOPIC</code>.
     */
    public final RegisteredUserTopic REGISTERED_USER_TOPIC = RegisteredUserTopic.REGISTERED_USER_TOPIC;

    /**
     * The table <code>menarini_dev.ROLE</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * No further instances allowed
     */
    private DbSchema() {
        super("menarini_dev", null);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            EventEnrollment.EVENT_ENROLLMENT,
            RegisteredUser.REGISTERED_USER,
            RegisteredUserRole.REGISTERED_USER_ROLE,
            RegisteredUserTopic.REGISTERED_USER_TOPIC,
            Role.ROLE
        );
    }
}
