/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.utils;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import com.jakala.menarini.core.entities.Event;
import com.jakala.menarini.core.entities.EventEnrollment;
import com.jakala.menarini.core.entities.EventSessionDate;
import com.jakala.menarini.core.entities.EventSpeaker;
import com.jakala.menarini.core.entities.EventTopic;
import com.jakala.menarini.core.entities.Location;
import com.jakala.menarini.core.entities.MagazineSubscription;
import com.jakala.menarini.core.entities.NewsletterSubscription;
import com.jakala.menarini.core.entities.RegisteredUser;
import com.jakala.menarini.core.entities.RegisteredUserRole;
import com.jakala.menarini.core.entities.RegisteredUserTopic;
import com.jakala.menarini.core.entities.Role;
import com.jakala.menarini.core.entities.Speaker;
import com.jakala.menarini.core.entities.Topic;
import com.jakala.menarini.core.entities.Venue;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbSchema extends SchemaImpl {

    private static final long serialVersionUID = -858789795;

    /**
     * The reference instance of <code>menarini_dev</code>
     */
    public static final DbSchema MENARINI = new DbSchema();

    /**
     * The table <code>menarini_dev.EVENT</code>.
     */
    public final Event EVENT = com.jakala.menarini.core.entities.Event.EVENT;

    /**
     * The table <code>menarini_dev.EVENT_ENROLLMENT</code>.
     */
    public final EventEnrollment EVENT_ENROLLMENT = com.jakala.menarini.core.entities.EventEnrollment.EVENT_ENROLLMENT;

    /**
     * The table <code>menarini_dev.EVENT_SESSION_DATE</code>.
     */
    public final EventSessionDate EVENT_SESSION_DATE = com.jakala.menarini.core.entities.EventSessionDate.EVENT_SESSION_DATE;

    /**
     * The table <code>menarini_dev.EVENT_SPEAKER</code>.
     */
    public final EventSpeaker EVENT_SPEAKER = com.jakala.menarini.core.entities.EventSpeaker.EVENT_SPEAKER;

    /**
     * The table <code>menarini_dev.EVENT_TOPIC</code>.
     */
    public final EventTopic EVENT_TOPIC = com.jakala.menarini.core.entities.EventTopic.EVENT_TOPIC;

    /**
     * The table <code>menarini_dev.LOCATION</code>.
     */
    public final Location LOCATION = com.jakala.menarini.core.entities.Location.LOCATION;

    /**
     * The table <code>menarini_dev.MAGAZINE_SUBSCRIPTION</code>.
     */
    public final MagazineSubscription MAGAZINE_SUBSCRIPTION = com.jakala.menarini.core.entities.MagazineSubscription.MAGAZINE_SUBSCRIPTION;

    /**
     * The table <code>menarini_dev.NEWSLETTER_SUBSCRIPTION</code>.
     */
    public final NewsletterSubscription NEWSLETTER_SUBSCRIPTION = com.jakala.menarini.core.entities.NewsletterSubscription.NEWSLETTER_SUBSCRIPTION;

    /**
     * The table <code>menarini_dev.REGISTERED_USER</code>.
     */
    public final RegisteredUser REGISTERED_USER = com.jakala.menarini.core.entities.RegisteredUser.REGISTERED_USER;

    /**
     * The table <code>menarini_dev.REGISTERED_USER_ROLE</code>.
     */
    public final RegisteredUserRole REGISTERED_USER_ROLE = com.jakala.menarini.core.entities.RegisteredUserRole.REGISTERED_USER_ROLE;

    /**
     * The table <code>menarini_dev.REGISTERED_USER_TOPIC</code>.
     */
    public final RegisteredUserTopic REGISTERED_USER_TOPIC = com.jakala.menarini.core.entities.RegisteredUserTopic.REGISTERED_USER_TOPIC;

    /**
     * The table <code>menarini_dev.ROLE</code>.
     */
    public final Role ROLE = com.jakala.menarini.core.entities.Role.ROLE;

    /**
     * The table <code>menarini_dev.SPEAKER</code>.
     */
    public final Speaker SPEAKER = com.jakala.menarini.core.entities.Speaker.SPEAKER;

    /**
     * The table <code>menarini_dev.TOPIC</code>.
     */
    public final Topic TOPIC = com.jakala.menarini.core.entities.Topic.TOPIC;

    /**
     * The table <code>menarini_dev.VENUE</code>.
     */
    public final Venue VENUE = com.jakala.menarini.core.entities.Venue.VENUE;

    /**
     * No further instances allowed
     */
    private DbSchema() {
        super("menarini_dev", null);
    }



    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Event.EVENT,
            EventEnrollment.EVENT_ENROLLMENT,
            EventSessionDate.EVENT_SESSION_DATE,
            EventSpeaker.EVENT_SPEAKER,
            EventTopic.EVENT_TOPIC,
            Location.LOCATION,
            MagazineSubscription.MAGAZINE_SUBSCRIPTION,
            NewsletterSubscription.NEWSLETTER_SUBSCRIPTION,
            RegisteredUser.REGISTERED_USER,
            RegisteredUserRole.REGISTERED_USER_ROLE,
            RegisteredUserTopic.REGISTERED_USER_TOPIC,
            Role.ROLE,
            Speaker.SPEAKER,
            Topic.TOPIC,
            Venue.VENUE);
    }
}
