/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.utils;


import com.jakala.menarini.core.entities.EventEnrollment;
import com.jakala.menarini.core.entities.RegisteredUserRole;
import com.jakala.menarini.core.entities.RegisteredUserTopic;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in menarini_dev.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EVENT_ENROLLMENT_EVENT_ID = Internal.createIndex(DSL.name("event_id"), EventEnrollment.EVENT_ENROLLMENT, new OrderField[] { EventEnrollment.EVENT_ENROLLMENT.EVENT_ID }, false);
    public static final Index EVENT_ENROLLMENT_REGISTERED_USER_ID = Internal.createIndex(DSL.name("registered_user_id"), EventEnrollment.EVENT_ENROLLMENT, new OrderField[] { EventEnrollment.EVENT_ENROLLMENT.REGISTERED_USER_ID }, false);
    public static final Index REGISTERED_USER_ROLE_REGISTERED_USER_ID = Internal.createIndex(DSL.name("registered_user_id"), RegisteredUserRole.REGISTERED_USER_ROLE, new OrderField[] { RegisteredUserRole.REGISTERED_USER_ROLE.REGISTERED_USER_ID }, false);
    public static final Index REGISTERED_USER_TOPIC_REGISTERED_USER_ID = Internal.createIndex(DSL.name("registered_user_id"), RegisteredUserTopic.REGISTERED_USER_TOPIC, new OrderField[] { RegisteredUserTopic.REGISTERED_USER_TOPIC.REGISTERED_USER_ID }, false);
    public static final Index REGISTERED_USER_ROLE_ROLE_ID = Internal.createIndex(DSL.name("role_id"), RegisteredUserRole.REGISTERED_USER_ROLE, new OrderField[] { RegisteredUserRole.REGISTERED_USER_ROLE.ROLE_ID }, false);
    public static final Index REGISTERED_USER_TOPIC_TOPIC_ID = Internal.createIndex(DSL.name("topic_id"), RegisteredUserTopic.REGISTERED_USER_TOPIC, new OrderField[] { RegisteredUserTopic.REGISTERED_USER_TOPIC.TOPIC_ID }, false);
}
