/*
 * This file is generated by jOOQ.
 */
package com.jakala.menarini.core.entities.utils;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import com.jakala.menarini.core.entities.Event;
import com.jakala.menarini.core.entities.EventEnrollment;
import com.jakala.menarini.core.entities.EventSessionDate;
import com.jakala.menarini.core.entities.EventSpeaker;
import com.jakala.menarini.core.entities.EventTopic;
import com.jakala.menarini.core.entities.Location;
import com.jakala.menarini.core.entities.MagazineSubscription;
import com.jakala.menarini.core.entities.NewsletterSubscription;
import com.jakala.menarini.core.entities.RegisteredUser;
import com.jakala.menarini.core.entities.RegisteredUserRole;
import com.jakala.menarini.core.entities.RegisteredUserTopic;
import com.jakala.menarini.core.entities.Role;
import com.jakala.menarini.core.entities.Speaker;
import com.jakala.menarini.core.entities.Topic;
import com.jakala.menarini.core.entities.Venue;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>menarini_dev</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EVENT_LOCATION_ID = Indexes0.EVENT_LOCATION_ID;
    public static final Index EVENT_PRIMARY = Indexes0.EVENT_PRIMARY;
    public static final Index EVENT_VENUE_ID = Indexes0.EVENT_VENUE_ID;
    public static final Index EVENT_ENROLLMENT_EVENT_ID = Indexes0.EVENT_ENROLLMENT_EVENT_ID;
    public static final Index EVENT_ENROLLMENT_PRIMARY = Indexes0.EVENT_ENROLLMENT_PRIMARY;
    public static final Index EVENT_ENROLLMENT_REGISTERED_USER_ID = Indexes0.EVENT_ENROLLMENT_REGISTERED_USER_ID;
    public static final Index EVENT_SESSION_DATE_EVENT_ID = Indexes0.EVENT_SESSION_DATE_EVENT_ID;
    public static final Index EVENT_SESSION_DATE_LOCATION_ID = Indexes0.EVENT_SESSION_DATE_LOCATION_ID;
    public static final Index EVENT_SESSION_DATE_PRIMARY = Indexes0.EVENT_SESSION_DATE_PRIMARY;
    public static final Index EVENT_SESSION_DATE_VENUE_ID = Indexes0.EVENT_SESSION_DATE_VENUE_ID;
    public static final Index EVENT_SPEAKER_EVENT_ID = Indexes0.EVENT_SPEAKER_EVENT_ID;
    public static final Index EVENT_SPEAKER_PRIMARY = Indexes0.EVENT_SPEAKER_PRIMARY;
    public static final Index EVENT_SPEAKER_SPEAKER_ID = Indexes0.EVENT_SPEAKER_SPEAKER_ID;
    public static final Index EVENT_TOPIC_EVENT_ID = Indexes0.EVENT_TOPIC_EVENT_ID;
    public static final Index EVENT_TOPIC_PRIMARY = Indexes0.EVENT_TOPIC_PRIMARY;
    public static final Index EVENT_TOPIC_TOPIC_ID = Indexes0.EVENT_TOPIC_TOPIC_ID;
    public static final Index LOCATION_PRIMARY = Indexes0.LOCATION_PRIMARY;
    public static final Index MAGAZINE_SUBSCRIPTION_PRIMARY = Indexes0.MAGAZINE_SUBSCRIPTION_PRIMARY;
    public static final Index MAGAZINE_SUBSCRIPTION_REGISTERED_USER_ID = Indexes0.MAGAZINE_SUBSCRIPTION_REGISTERED_USER_ID;
    public static final Index NEWSLETTER_SUBSCRIPTION_PRIMARY = Indexes0.NEWSLETTER_SUBSCRIPTION_PRIMARY;
    public static final Index NEWSLETTER_SUBSCRIPTION_REGISTERED_USER_ID = Indexes0.NEWSLETTER_SUBSCRIPTION_REGISTERED_USER_ID;
    public static final Index REGISTERED_USER_PRIMARY = Indexes0.REGISTERED_USER_PRIMARY;
    public static final Index REGISTERED_USER_ROLE_PRIMARY = Indexes0.REGISTERED_USER_ROLE_PRIMARY;
    public static final Index REGISTERED_USER_ROLE_REGISTERED_USER_ID = Indexes0.REGISTERED_USER_ROLE_REGISTERED_USER_ID;
    public static final Index REGISTERED_USER_ROLE_ROLE_ID = Indexes0.REGISTERED_USER_ROLE_ROLE_ID;
    public static final Index REGISTERED_USER_TOPIC_PRIMARY = Indexes0.REGISTERED_USER_TOPIC_PRIMARY;
    public static final Index REGISTERED_USER_TOPIC_REGISTERED_USER_ID = Indexes0.REGISTERED_USER_TOPIC_REGISTERED_USER_ID;
    public static final Index REGISTERED_USER_TOPIC_TOPIC_ID = Indexes0.REGISTERED_USER_TOPIC_TOPIC_ID;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index SPEAKER_PRIMARY = Indexes0.SPEAKER_PRIMARY;
    public static final Index TOPIC_PRIMARY = Indexes0.TOPIC_PRIMARY;
    public static final Index VENUE_LOCATION_ID = Indexes0.VENUE_LOCATION_ID;
    public static final Index VENUE_PRIMARY = Indexes0.VENUE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EVENT_LOCATION_ID = Internal.createIndex("location_id", Event.EVENT, new OrderField[] { Event.EVENT.LOCATION_ID }, false);
        public static Index EVENT_PRIMARY = Internal.createIndex("PRIMARY", Event.EVENT, new OrderField[] { Event.EVENT.ID }, true);
        public static Index EVENT_VENUE_ID = Internal.createIndex("venue_id", Event.EVENT, new OrderField[] { Event.EVENT.VENUE_ID }, false);
        public static Index EVENT_ENROLLMENT_EVENT_ID = Internal.createIndex("event_id", EventEnrollment.EVENT_ENROLLMENT, new OrderField[] { EventEnrollment.EVENT_ENROLLMENT.EVENT_ID }, false);
        public static Index EVENT_ENROLLMENT_PRIMARY = Internal.createIndex("PRIMARY", EventEnrollment.EVENT_ENROLLMENT, new OrderField[] { EventEnrollment.EVENT_ENROLLMENT.ID }, true);
        public static Index EVENT_ENROLLMENT_REGISTERED_USER_ID = Internal.createIndex("registered_user_id", EventEnrollment.EVENT_ENROLLMENT, new OrderField[] { EventEnrollment.EVENT_ENROLLMENT.REGISTERED_USER_ID }, false);
        public static Index EVENT_SESSION_DATE_EVENT_ID = Internal.createIndex("event_id", EventSessionDate.EVENT_SESSION_DATE, new OrderField[] { EventSessionDate.EVENT_SESSION_DATE.EVENT_ID }, false);
        public static Index EVENT_SESSION_DATE_LOCATION_ID = Internal.createIndex("location_id", EventSessionDate.EVENT_SESSION_DATE, new OrderField[] { EventSessionDate.EVENT_SESSION_DATE.LOCATION_ID }, false);
        public static Index EVENT_SESSION_DATE_PRIMARY = Internal.createIndex("PRIMARY", EventSessionDate.EVENT_SESSION_DATE, new OrderField[] { EventSessionDate.EVENT_SESSION_DATE.ID }, true);
        public static Index EVENT_SESSION_DATE_VENUE_ID = Internal.createIndex("venue_id", EventSessionDate.EVENT_SESSION_DATE, new OrderField[] { EventSessionDate.EVENT_SESSION_DATE.VENUE_ID }, false);
        public static Index EVENT_SPEAKER_EVENT_ID = Internal.createIndex("event_id", EventSpeaker.EVENT_SPEAKER, new OrderField[] { EventSpeaker.EVENT_SPEAKER.EVENT_ID }, false);
        public static Index EVENT_SPEAKER_PRIMARY = Internal.createIndex("PRIMARY", EventSpeaker.EVENT_SPEAKER, new OrderField[] { EventSpeaker.EVENT_SPEAKER.ID }, true);
        public static Index EVENT_SPEAKER_SPEAKER_ID = Internal.createIndex("speaker_id", EventSpeaker.EVENT_SPEAKER, new OrderField[] { EventSpeaker.EVENT_SPEAKER.SPEAKER_ID }, false);
        public static Index EVENT_TOPIC_EVENT_ID = Internal.createIndex("event_id", EventTopic.EVENT_TOPIC, new OrderField[] { EventTopic.EVENT_TOPIC.EVENT_ID }, false);
        public static Index EVENT_TOPIC_PRIMARY = Internal.createIndex("PRIMARY", EventTopic.EVENT_TOPIC, new OrderField[] { EventTopic.EVENT_TOPIC.ID }, true);
        public static Index EVENT_TOPIC_TOPIC_ID = Internal.createIndex("topic_id", EventTopic.EVENT_TOPIC, new OrderField[] { EventTopic.EVENT_TOPIC.TOPIC_ID }, false);
        public static Index LOCATION_PRIMARY = Internal.createIndex("PRIMARY", Location.LOCATION, new OrderField[] { Location.LOCATION.ID }, true);
        public static Index MAGAZINE_SUBSCRIPTION_PRIMARY = Internal.createIndex("PRIMARY", MagazineSubscription.MAGAZINE_SUBSCRIPTION, new OrderField[] { MagazineSubscription.MAGAZINE_SUBSCRIPTION.ID }, true);
        public static Index MAGAZINE_SUBSCRIPTION_REGISTERED_USER_ID = Internal.createIndex("registered_user_id", MagazineSubscription.MAGAZINE_SUBSCRIPTION, new OrderField[] { MagazineSubscription.MAGAZINE_SUBSCRIPTION.REGISTERED_USER_ID }, false);
        public static Index NEWSLETTER_SUBSCRIPTION_PRIMARY = Internal.createIndex("PRIMARY", NewsletterSubscription.NEWSLETTER_SUBSCRIPTION, new OrderField[] { NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.ID }, true);
        public static Index NEWSLETTER_SUBSCRIPTION_REGISTERED_USER_ID = Internal.createIndex("registered_user_id", NewsletterSubscription.NEWSLETTER_SUBSCRIPTION, new OrderField[] { NewsletterSubscription.NEWSLETTER_SUBSCRIPTION.REGISTERED_USER_ID }, false);
        public static Index REGISTERED_USER_PRIMARY = Internal.createIndex("PRIMARY", RegisteredUser.REGISTERED_USER, new OrderField[] { RegisteredUser.REGISTERED_USER.ID }, true);
        public static Index REGISTERED_USER_ROLE_PRIMARY = Internal.createIndex("PRIMARY", RegisteredUserRole.REGISTERED_USER_ROLE, new OrderField[] { RegisteredUserRole.REGISTERED_USER_ROLE.ID }, true);
        public static Index REGISTERED_USER_ROLE_REGISTERED_USER_ID = Internal.createIndex("registered_user_id", RegisteredUserRole.REGISTERED_USER_ROLE, new OrderField[] { RegisteredUserRole.REGISTERED_USER_ROLE.REGISTERED_USER_ID }, false);
        public static Index REGISTERED_USER_ROLE_ROLE_ID = Internal.createIndex("role_id", RegisteredUserRole.REGISTERED_USER_ROLE, new OrderField[] { RegisteredUserRole.REGISTERED_USER_ROLE.ROLE_ID }, false);
        public static Index REGISTERED_USER_TOPIC_PRIMARY = Internal.createIndex("PRIMARY", RegisteredUserTopic.REGISTERED_USER_TOPIC, new OrderField[] { RegisteredUserTopic.REGISTERED_USER_TOPIC.ID }, true);
        public static Index REGISTERED_USER_TOPIC_REGISTERED_USER_ID = Internal.createIndex("registered_user_id", RegisteredUserTopic.REGISTERED_USER_TOPIC, new OrderField[] { RegisteredUserTopic.REGISTERED_USER_TOPIC.REGISTERED_USER_ID }, false);
        public static Index REGISTERED_USER_TOPIC_TOPIC_ID = Internal.createIndex("topic_id", RegisteredUserTopic.REGISTERED_USER_TOPIC, new OrderField[] { RegisteredUserTopic.REGISTERED_USER_TOPIC.TOPIC_ID }, false);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index SPEAKER_PRIMARY = Internal.createIndex("PRIMARY", Speaker.SPEAKER, new OrderField[] { Speaker.SPEAKER.ID }, true);
        public static Index TOPIC_PRIMARY = Internal.createIndex("PRIMARY", Topic.TOPIC, new OrderField[] { Topic.TOPIC.ID }, true);
        public static Index VENUE_LOCATION_ID = Internal.createIndex("location_id", Venue.VENUE, new OrderField[] { Venue.VENUE.LOCATION_ID }, false);
        public static Index VENUE_PRIMARY = Internal.createIndex("PRIMARY", Venue.VENUE, new OrderField[] { Venue.VENUE.ID }, true);
    }
}
